"""empty message

Revision ID: 370806b814bc
Revises: 2807edd385a2
Create Date: 2021-12-15 01:07:53.385794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370806b814bc'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
